name: Octopus Plugin
description: The Octopus plugin will allow you to perform deployments with Octopus.
version: 1.0
icon: https://cdn.jsdelivr.net/gh/clarive/cla-octopus-plugin/public/icon/octopus.svg?sanitize=true
url: https://github.com/clarive/cla-octopus-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-octopus-plugin
